### ISSUE TITLE
Project build error

### ISSUE THREAD

**Issue by sebillen** [asklar/WinRTComponent#1]
Hi,
Follow you post to understand WinRTComponent.
Download it, open on Visual Studio 2019 and build solution.
Got following error
1>------ Build started: Project: RuntimeComponent1, Configuration: Release Any CPU ------
1>  RuntimeComponent1 -> C:\Users\sebillen\Downloads\WinRTComponent-master\bin\Release\RuntimeComponent1.winmd
2>------ Build started: Project: BlankApp1, Configuration: Release Win32 ------
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1850,5): warning : The referenced project '..\..\WinRTComponent\RuntimeComponent1.csproj' does not exist.
2>C:\Users\sebillen\Downloads\WinRTComponent-master\BlankApp1\BlankApp1.vcxproj(195,5): error : This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\..\WinRTComponent\packages\Microsoft.Windows.CppWinRT.2.0.200316.3\build\native\Microsoft.Windows.CppWinRT.props.
2>Done building project "BlankApp1.vcxproj" -- FAILED.
========== Build: 1 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

Any idea?
Regards,

**Comment by asklar** [comment]
@sebillen try running nuget restore on the sln file
